"""add_plan_and_url_validity

Revision ID: 8ec67c7fbb5f
Revises: 001_initial_schema
Create Date: 2026-07-08 10:41:54.230269
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8ec67c7fbb5f'
down_revision: Union[str, None] = '001_initial_schema'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('merchants', sa.Column('plan', sa.String(length=50), server_default='Free', nullable=False))
    op.add_column('merchants', sa.Column('urls_created_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('urls', sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('urls', 'valid_until')
    op.drop_column('merchants', 'urls_created_count')
    op.drop_column('merchants', 'plan')
    # ### end Alembic commands ###
